### ISSUE TITLE
Failed to receive trace information from dotnet autoinstrumentation

### ISSUE THREAD

**Issue by shawnho1018** [observIQ/bindplane-agent#1381]
I am using kubernetes node bindplane agent to collect my dotnet core app. I configured a opentelemetry (OTLP) processor to retrieve log/metrics/traces. I could see log and metrics were successfully received in bindplane ops agent; however, the trace information is missing. 
I sniffed the packet and confirmed the traceparent information is properly generated in the http header but my bindplane ops agent showed no traces was received from the app.
My bindplane version is 1.36.0

**Comment by Dylan-M** [comment]
Shawn,

I assume you mean OTLP receiver, rather than processor. That is the first step. After that, the OTLP trace instrumentation, even autoinstrumentation, has to be pointed to that receiver correctly. The K8s endpoint is very specific (I'll be asking another engineer to respond with the correct endpoint information, as he knows it well), and if it is entered incorrectly you will see exactly what you are experiencing.

If my assumption is wrong, and you actually did add a processor instead of a receiver, that is also an issue.

I'll have the other engineer tag in with more detailed information about that endpoint now.

**Comment by jsirianni** [comment]
Hi @shawnho1018, if you are using the node agent with the OTLP source, you can reference [this doc for the proper endpoints](https://observiq.com/docs/integrations/sources/opentelemetry#kubernetes).

Can you confirm that your instrumented applications are targeting one of the endpoints outlined in that doc? Also, are you using gRPC or HTTP?

**Comment by BinaryFissionGames** [comment]
This issue has been stale for a while, so I'm going to close it for the time being. Please feel free to open a new issue if you are still running into problems, or feel free to reach out in our [public Slack](https://observiq.com/support-bindplaneop/)!
